# Generated by Django 4.2.3 on 2023-07-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestatus',
            old_name='device_id',
            new_name='device',
        ),
    ]
