# Generated by Django 4.2.3 on 2023-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusinfo', '0002_rename_device_id_devicestatus_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
